ALTER TABLE comercio.COMERCIO ADD IMG_HASH_CODE INT;
GO

ALTER TABLE banner.BANNER ADD IMG_HASH_CODE INT
GO

ALTER TABLE comunicacao.AGENDA_CULTURAL ADD IMG_HASH_CODE INT
GO

ALTER TABLE relac.DIALOGO ADD IMG_HASH_CODE INT
GO

ALTER TABLE comercio.PRODUTO ADD IMG_HASH_CODE INT
GO

ALTER TABLE comercio.PRODUTO ADD IMG_HASH_CODE INT
GO

ALTER TABLE dbo.NOTICIA ADD IMG_HASH_CODE INT
GO

ALTER TABLE info.INFO ADD IMG_HASH_CODE INT
GO
